apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-svc
  namespace: hospital-llm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-svc
  template:
    metadata:
      labels:
        app: rabbitmq-svc
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.13-management
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: hospital
            - name: RABBITMQ_DEFAULT_PASS
              value: hospitalpass
          ports:
            - containerPort: 5672
              name: amqp
            - containerPort: 15672
              name: management
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-svc
  namespace: hospital-llm
spec:
  selector:
    app: rabbitmq-svc
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: management
      port: 15672
      targetPort: 15672
